# Generated by Django 2.1.7 on 2019-02-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
