# Generated by Django 2.1.7 on 2019-02-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190224_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='default.png', upload_to='image/%Y/%m/%d'),
        ),
    ]
